### ISSUE TITLE
sh: -c: option requires an argument

### ISSUE THREAD

**Issue by stepupit-work** [dgageot/demoit#59] opened 2020-02-03 07:18 UTC
When I run it using 
demoit sample or demoit dev sample
On browser it always says "sh: -c: option requires an argument"
go get -u github.com/dgageot/demoit

I am running your sample project without any change.

**Comment by sebght** [comment] 2020-03-06 10:23
I think this refers to #2 😉 
FYI, just go to http://localhost:8888/ instead

**Comment by dgageot** [comment] 2022-06-17 06:10
duplicate of https://github.com/dgageot/demoit/issues/2

**Closed by dgageot** 2022-06-17 06:10 UTC
